session_name: feathers
windows:
  - window_name: feathers
    start_directory: ~/projects/personal/feathers
    focus: true
    panes:
      - nvim
  - window_name: bubbles
    start_directory: ~/projects/learning/go/charm/bubbles
    panes:
      - nvim
  - window_name: textual
    start_directory: ~/projects/learning/python/textual
    panes:
      - nvim
  - window_name: term
    start_directory: ~/projects/personal/feathers
