session_name: learn-ai
windows:
  - window_name: learn-ai
    start_directory: ~/projects/personal/learn-ai
    focus: true
    panes:
      - nvim
  - window_name: term
    start_directory: ~/projects/personal/learn-ai
