session_name: nvim
windows:
  - window_name: code
    start_directory: ~/.config/LazyVim
    focus: true
    panes:
      - nvim-lazy
  - window_name: dotfiles
    start_directory: ~/.dotfiles
    panes:
      - nvim
  - window_name: LazyVim
    start_directory: ~/projects/learning/nvim/LazyVim
    panes:
      - nvim
  - window_name: NvChad
    start_directory: ~/.config/NvChad
    panes:
      - nvim
  - window_name: folke-dot
    start_directory: ~/projects/learning/dotfiles/folke-dot
    panes:
      - nvim
  - window_name: term
    start_directory: ~/.config
