########################## Config ###############################

# Change prefix key
unbind C-b
set -g prefix C-a

# Index from 1
set -g base-index 1

# TODO: Not sure how this work
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# Enable vim mode, default is emacs
set-window-option -g mode-keys vi

# vim like pane switching
bind -r C-a last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R
bind -r J select-pane -t :.+

# more memorable split keys
bind -r - split-window -v
bind -r | split-window -h

# mouse support
set -g mouse on

########################## Plugins ###############################
# Use prefix-I to install plugins

# List of plugins
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'dracula/tmux'
set -g @dracula-show-powerline true
set -g @dracula-show-left-icon session
set -g @dracula-plugins "cpu-usage ram-usage"

# Provide
## prefix-R to reload config
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'tmux-plugins/tmux-resurrect' # add `Prefix C-s` to save and `Prefix C-r` to reload
set -g @plugin 'tmux-plugins/tmux-continuum' # auto save resurrect sessions every 15 minutes
set -g @resurrect-strategy-nvim 'session' # restore nvim sessions :O

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
