git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --syntax-theme=Dracula
os:
  edit: "nvim"

customCommands:
  - key: "<c-g>"
    command: "gh pr create --fill --web"
    context: "global"
    loadingText: "Creating pull request on GitHub"

  - key: "<c-D>"
    command: "git remote prune {{.SelectedRemote.Name}}"
    context: "remotes"
    loadingText: "Pruning..."
    description: "prune deleted remote branches"

  - key: "D"
    command: "git branch --merged master | grep -v '^[ *]*master$' | xargs git branch -d"
    context: "localBranches"
    loadingText: "Pruning..."
    description: "prune local branches that have been merged to master"

  - key: "C"
    command: "git cz c"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true

  - key: "<c-u>"
    command: 'git add . && git commit -m "update" && git push'
    context: "global"
    description: 'Commit all as "update" and push'
