git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --syntax-theme=Dracula
os:
  edit: "nvim"
customCommands:
  - key: "<c-g>"
    command: "gh pr create --fill --web"
    context: "global"
    loadingText: "Creating pull request on GitHub"
  - key: "<c-D>"
    command: "git remote prune {{.SelectedRemote.Name}}"
    context: "remotes"
    loadingText: "Pruning..."
    description: "prune deleted remote branches"
  - key: "D"
    command: "git branch --merged master | grep -v '^[ *]*master$' | xargs git branch -d"
    context: "localBranches"
    loadingText: "Pruning..."
    description: "prune local branches that have been merged to master"
  - key: "C"
    command: "git cz c"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    output: terminal
  - key: "<c-u>"
    command: 'git add . && git commit -m "update" && git push'
    context: "global"
    description: 'Commit all as "update" and push'
  - key: "t"
    command: "git checkout --theirs {{.SelectedFile.Name | quote}} && git add {{.SelectedFile.Name | quote}}"
    context: "files"
    description: "Pick their changes for this file"
    loadingText: "Resolving conflict using their changes..."
  - key: "m"
    command: "git checkout --ours {{.SelectedFile.Name | quote}} && git add {{.SelectedFile.Name | quote}}"
    context: "files"
    description: "Pick our changes for this file"
    loadingText: "Resolving conflict using our changes..."
