wtf:
  colors:
    border:
      focusable: "#80ffea"
      focused: "#9580ff"
      normal: gray
    checked: "#ff80bf"
    highlight:
      fore: "#ff80bf"
      back: white 
    rows:
      even: "#ff80bf" 
      odd: white
    text: white
    title: "#9580ff"
  grid:
    # How _wide_ the columns are, in terminal characters. In this case we have
    # four columns, each of which are 35 characters wide.
    columns: [32, 32, 32, 32, 32, 32, 32]
    # How _high_ the rows are, in terminal lines. In this case we have four rows
    # that support ten line of text and one of four.
    rows: [10, 10, 10, 10, 10]
  refreshInterval: 1
  openFileUtil: "open"
  navigation:
    shortcuts: true
  term: "xterm-256color"
  mods:
    # You can have multiple widgets of the same type.
    # The "key" is the name of the widget and the type is the actual
    # widget you want to implement.
    ip:
      type: ipinfo
      title: "My IP"
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 0
        left: 0
        height: 1
        width: 2
      refreshInterval: 150
    security_info:
      type: security
      title: "Staying safe"
      enabled: true
      position:
        top: 0
        left: 2
        height: 1
        width: 1
      refreshInterval: 3600
    news:
      type: hackernews
      title: "HackerNews"
      enabled: true
      numberOfStories: 10
      position:
        top: 1
        left: 0
        height: 1
        width: 3
      storyType: top
      refreshInterval: 900
