[packages]
brew_taps = ["aws/tap", "hashicorp/tap", "homebrew/bundle", "TylerBrock/saw"]

[packages.core]
brews = [
  "age",
  "bash",
  "bat",
  "cmake",
  "coreutils",
  "direnv",
  "dockutil",
  "eza",
  "fd",
  "findutils",
  "fzf",
  "gawk",
  "gh",
  "git",
  "git-delta",
  "git-extras",
  "gnu-getopt",
  "gnu-indent",
  "gnu-sed",
  "gnu-units",
  "gnu-tar",
  "gnutls",
  "grep",
  "jesseduffield/lazygit/lazygit",
  "neovim",
  "ripgrep",
  "ruby",
  "stow",
  "tmux",
  "tmuxp",
  "tree",
  "wget",
  "z",
]
casks = [
  "1password",
  "1password-cli",
  "firefox",
  "hammerspoon",
  "kitty",
  "visual-studio-code",
]

[packages.utils]
brews = [
  "act",
  "commitizen",
  "dive",
  "dua-cli",
  "glow",
  "gum",
  "homeassistant-cli",
  "htop",
  "httpie",
  "mods",
  "neofetch",
  "slides",
  "ssh-copy-id",
  "tz",
  "urlview",
  "wordnet",
  "wtfutil",
]
casks = [
  "docker",
  "google-chrome",
  "logseq",
  "notion",
  "obsidian",
  "spotify",
  "font-consolas-for-powerline",
  "font-fira-code",
  "font-fira-code-nerd-font",
  "font-fira-mono-nerd-font",
  "font-ia-writer-duo",
  "font-ia-writer-mono",
  "font-ia-writer-quattro",
  "font-inter",
  "font-meslo-lg-nerd-font",
  "font-menlo-for-powerline",
  "font-open-sans",
  "font-patrick-hand",
  "font-patrick-hand-sc",
  "font-roboto-mono",
  "font-roboto-mono-nerd-font",
  "font-roboto",
  "font-sf-mono",
  "font-hack-nerd-font",
  "font-ubuntu-mono-nerd-font",
  "font-jetbrains-mono-nerd-font",
]

[packages.extras]
brews = ["agg", "asciinema", "imagemagick", "pandoc", "svn"]
casks = [
  "discord",
  "dropbox",
  "expressvpn",
  "google-drive",
  "kindle",
  "sourcetree",
  "tailscale",
]

[packages.lang_json]
brews = ["jid", "jless", "jq"]

[packages.lang_bash]
brews = ["bats-core", "shellcheck"]

[packages.lang_lua]
brews = ["lua", "luajit", "luarocks", "stylua"]

[packages.lang_python]
brews = ["python", "pipenv", "poetry", "pyenv"]

[packages.lang_go]
brews = ["go", "golangci-lint"]

[packages.lang_node]
brews = ["fnm"]

[packages.lang_aws]
brews = ["awscli", "aws-sam-cli", "saw", "steampipe"]

[packages.lang_terraform]
brews = ["hashicorp/tap/terraform"]

[packages.lang_k8s]
brews = [
  "helm",
  "krew",
  "kubebuilder",
  "kubectl",
  "kubevela",
  "kustomize",
  "k9s",
  "minikube",
  "tilt",
]
casks = ["kui"]
