# Start AeroSpace at login
start-at-login = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 0

# Possible values: tiles|accordion
default-root-container-layout = 'accordion'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = true

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 2
inner.vertical = 2
outer.left = 2
outer.bottom = 2
outer.top = 2
outer.right = 2

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# Disable default mac shortcuts
cmd-h = []     # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"

# # See: https://nikitabobko.github.io/AeroSpace/commands#focus
# alt-h = 'focus left'
# alt-j = 'focus down'
# alt-k = 'focus up'
# alt-l = 'focus right'
#
# # See: https://nikitabobko.github.io/AeroSpace/commands#move
# alt-shift-h = 'move left'
# alt-shift-j = 'move down'
# alt-shift-k = 'move up'
# alt-shift-l = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-1 = 'workspace work-one'
alt-2 = 'workspace work-two'
alt-3 = 'workspace meeting'
alt-4 = 'workspace comms'
alt-5 = 'workspace personal'
alt-6 = 'workspace llm'
alt-7 = 'workspace chess'
alt-9 = 'workspace scratchpad'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-1 = 'move-node-to-workspace work-one'
alt-shift-2 = 'move-node-to-workspace work-two'
alt-shift-3 = 'move-node-to-workspace meeting'
alt-shift-4 = 'move-node-to-workspace comms'
alt-shift-5 = 'move-node-to-workspace personal'
alt-shift-6 = 'move-node-to-workspace llm'
alt-shift-7 = 'move-node-to-workspace chess'
alt-shift-9 = 'move-node-to-workspace scratchpad'

alt-tab = 'workspace-back-and-forth'
alt-rightSquareBracket = 'move-workspace-to-monitor --wrap-around next'

alt-shift-l = 'mode layout'
alt-shift-m = 'mode manage'
alt-shift-u = 'mode launch'
alt-shift-comma = 'mode setting'

[mode.layout.binding]
t = 'layout tiles horizontal vertical'
a = 'layout accordion horizontal vertical'
f = 'layout floating'
esc = ['mode main']

[mode.manage.binding]
esc = ['mode main']

[mode.launch.binding]
esc = ['mode main']

[mode.setting.binding]
esc = ['reload-config', 'mode main']

[workspace-to-monitor-force-assignment]
meeting = 'main'

#####################################################
################### Examples ########################
#####################################################

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# You can uncomment the following lines to open up terminal with alt + enter shortcut (like in i3)
# alt-enter = '''exec-and-forget osascript -e '
# tell application "Terminal"
#     do script
#     activate
# end tell'
# '''
