# Keybindings and settings
bindkey -v # Enable vim bindings

ZVM_INSERT_MODE_CURSOR=$ZVM_CURSOR_BEAM
ZVM_NORMAL_MODE_CURSOR=$ZVM_CURSOR_BLOCK
ZVM_OPPEND_MODE_CURSOR=$ZVM_CURSOR_UNDERLINE

ZVM_VI_INSERT_ESCAPE_BINDKEY=jj
